language: csharp
solution: WhatIsHeDoing.Core.sln
mono: none
dotnet: 3.1.404
install:
  - dotnet restore
script:
  - dotnet build --configuration Release
  - dotnet test WhatIsHeDoing.Core.Tests/WhatIsHeDoing.Core.Tests.csproj
