version: 1.0.{build}
image: Visual Studio 2019
platform: Any CPU
before_build:
- choco install codecov opencover.portable
build_script:
- dotnet restore
- dotnet build --configuration Release
test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:test -filter:"+[WhatIsHeDoing.Core]* -[WhatIsHeDoing.Core.Tests]*" -output:coverage.xml
- codecov -f coverage.xml
artifacts:
  - path: 'WhatIsHeDoing.Core\bin\Release\WhatIsHeDoing.Core.*.nupkg'
    name: WhatIsHeDoing.Core NuGet package
    type: NuGetPackage
deploy:
  provider: NuGet
  api_key:
    secure: KqVldW1Pof+b3vMCnQVgAl33DjCV9UIqv3aVccTANPgeNfYadBXkLnPnGHbYmuaW
  skip_symbols: false
  artifact: /.*\.nupkg/
