version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
build_script:
- ps: >-
    dotnet restore

    dotnet build --configuration Release
test_script:
- ps: dotnet test --configuration Release .\WhatIsHeDoing.Core.Tests\WhatIsHeDoing.Core.Tests.csproj
artifacts:
  - path: 'WhatIsHeDoing.Core\bin\Release\WhatIsHeDoing.Core.*.nupkg'
    name: WhatIsHeDoing.Core NuGet package
    type: NuGetPackage
deploy:
  provider: NuGet
  api_key:
    secure: 0vvD9xkaKen4fUz/3PIi0hbKx6Nyggnvlv8/EOyMtzG/t9T4h/3pdJQJQGa9Tf1z
  skip_symbols: false
  artifact: /.*\.nupkg/
