version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
before_build:
- choco install codecov opencover.portable
build_script:
- dotnet restore
- dotnet build --configuration Release
test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[WhatIsHeDoing.Core]* -[WhatIsHeDoing.Core.Tests]*" -output:coverage.xml -oldstyle
- codecov -f coverage.xml
artifacts:
  - path: 'WhatIsHeDoing.Core\bin\Release\WhatIsHeDoing.Core.*.nupkg'
    name: WhatIsHeDoing.Core NuGet package
    type: NuGetPackage
deploy:
  provider: NuGet
  api_key:
    secure: GzI+541WvJLQ2V51SlkZ56jPtn1DZlFzRc42Dx1S030AZLPfNErAoXnivqqeIhv5
  skip_symbols: false
  artifact: /.*\.nupkg/
