version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
environment:
  SNYK_KEY:
    secure: 3Veu6SjQ3EG4CsnWwZC2/Tb5ckd2T9ym1wcCEzYnLcDiVO/4looeNn/pEMElOxbw
before_build:
- choco install opencover.portable
- choco install codecov
build_script:
- dotnet restore
- dotnet build --configuration Release
after_build:
- npm install snyk -g
- snyk auth %SNYK_KEY%
- cd WhatIsHeDoing.Core
- snyk test
- snyk monitor
test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[WhatIsHeDoing.Core]* -[WhatIsHeDoing.Core.Tests]*" -output:coverage.xml -oldstyle
- codecov -f coverage.xml
artifacts:
  - path: 'WhatIsHeDoing.Core\bin\Release\WhatIsHeDoing.Core.*.nupkg'
    name: WhatIsHeDoing.Core NuGet package
    type: NuGetPackage
deploy:
  provider: NuGet
  api_key:
    secure: 0vvD9xkaKen4fUz/3PIi0hbKx6Nyggnvlv8/EOyMtzG/t9T4h/3pdJQJQGa9Tf1z
  skip_symbols: false
  artifact: /.*\.nupkg/
